/*
Copyright (c) [2023-2024] [AppLayer Developers]

This software is distributed under the MIT License.
See the LICENSE.txt file in the project root for more information.
*/

#ifndef SNAILTRACEROPTIMIZED_H
#define SNAILTRACEROPTIMIZED_H

#include <tuple>

#include "../dynamiccontract.h"
#include "../variables/safebytes.h"
#include "../variables/safeint.h"
#include "../variables/safetuple.h"
#include "../variables/safeuint.h"
#include "../variables/safevector.h"
#include "../../utils/utils.h" // bytes alias

/**
 * Variant of SnailTracer that uses int136 instead of int256.
 * Any number lower than that will cause calculation errors like SIGFPE (division by zero),
 * under/overflows or simply lack of bit space for results in the original contract's math logic.
 */
class SnailTracerOptimized : public DynamicContract {
  private:
    /// Enum for light-altering surface types.
    enum Material { Diffuse, Specular, Refractive };

    /// Enum for primitive geometric types.
    enum Primitive { PSphere, PTriangle };

    /// Struct for a 3-axis vector (X, Y, Z).
    using Vector = std::tuple<int136_t, int136_t, int136_t>;

    /// Struct for a parametric line (origin, direction, depth, refract).
    using Ray = std::tuple<Vector, Vector, int136_t, bool>;

    /// Struct for a physical sphere to intersect light rays with (radius, position, emission, color, reflection).
    using Sphere = std::tuple<int136_t, Vector, Vector, Vector, Material>;

    /// Struct for a physical triangle to intersect light rays with (a, b, c, normal, emission, color, reflection).
    using Triangle = std::tuple<Vector, Vector, Vector, Vector, Vector, Vector, Material>;

    using SVector = SafeTuple<int136_t, int136_t, int136_t>; ///< SafeVar version of Vector.
    using SRay = SafeTuple<Vector, Vector, int136_t, bool>; ///< SafeVar version of Ray.
    using SSphereArr = SafeVector<Sphere>; ///< SafeVar version of an array of Spheres.
    using STriangleArr = SafeVector<Triangle>; ///< SafeVar version of an array of Triangles.

    SafeInt136_t width_; ///< Width of the image to be generated (fixed for life).
    SafeInt136_t height_; ///< Height of the image to be generated (fixed for life).
    SafeBytes buffer_; ///< Ephemeral buffer to accumulate image traces.
    SafeUint32_t seed_;  ///< Trivial linear congruential pseudo-random seed generated by rand().
    SRay camera_;  ///< Camera position for image assembly.
    SVector deltaX_; ///< Horizontal FoV angle increment per image pixel.
    SVector deltaY_; ///< Vertical FoV angle increment per image pixel.
    SSphereArr spheres_; ///< Array of spheres defining the scene to render.
    STriangleArr triangles_; ///< Array of triangles defining the scene to render.

    void registerContractFunctions() override; ///< Register the contract functions.

  public:
    /// The constructor argument types.
    using ConstructorArguments = std::tuple<int136_t, int136_t>;

    /**
     * Constructor to be used when creating a new contract.
     * @param w Width to initialize with.
     * @param h Height to initialize with.
     * @param address The address where the contract will be deployed.
     * @param creator The address of the creator of the contract.
     * @param chainId The chain where the contract wil be deployed.
     */
    SnailTracerOptimized(
      int136_t w, int136_t h, const Address& address, const Address& creator, const uint64_t& chainId
    );

    /**
     * Constructor for loading contract from DB.
     * @param address The address where the contract will be deployed.
     * @param db Reference to the database object.
     */
    SnailTracerOptimized(const Address& address, const DB& db);

    ~SnailTracerOptimized() override; ///< Destructor.

    /**
     * Trace a single pixel of the configured image.
     * Meant to be used specifically for high SPP renderings which would have a huge overhead otherwise.
     * @param x The X position of the pixel to trace.
     * @param y The Y position of the pixel to trace.
     * @param spp The SPP (Samples Per Pixel) of the pixel to trace.
     * @return The R, G and B values respectively.
     */
    std::tuple<uint8_t, uint8_t, uint8_t> TracePixel(const int136_t& x, const int136_t& y, const uint136_t& spp);

    /**
     * Trace a single horizontal scanline of the configured image.
     * Used for lower SPP rendering to avoid overhead of by-pixel calls.
     * @param y The Y position of the line to trace.
     * @param spp The SPP (Samples Per Pixel) of the line to trace.
     * @return The RGB value pixel array.
     */
    Bytes TraceScanline(const int136_t& y, const int136_t& spp);

    /**
     * Trace an entire image of the configured scene.
     * Used only for very small images and SPP values to cut down on cumulative gas and memory costs.
     * @param spp The SPP (Samples Per Pixel) of the image to trace.
     * @return The RGB pixel value array, top-down, left-to-right.
     */
    Bytes TraceImage(const int136_t& spp);

    /**
     * Set up an ephemeral image configuration and trace a select few
     * hand picked pixels from it to measure execution performance.
     * @return The R, G and B values respectively.
     */
    std::tuple<uint8_t, uint8_t, uint8_t> Benchmark();

    /**
     * Execute path tracing for a single pixel of the result image.
     * @param x The X position of the pixel to trace.
     * @param y The Y position of the pixel to trace.
     * @param spp The SPP (Samples Per Pixel) of the pixel to trace.
     * @return The RGB color vector normalized to [0, 256) value range.
     */
    Vector trace(const int136_t& x, const int136_t& y, const int136_t& spp);

    uint32_t rand(); ///< Trivial linear congruential pseudo-random number generator. Returns a new random seed.

    /**
     * Bound an int value to the allowed [0, 1] range.
     * @param x The value to clamp.
     * @return The clamped value.
     */
    int136_t clamp(const int136_t& x);

    /**
     * Calculate the square root of an int value based on the Babylonian method.
     * @param x The value to calculate the square root from.
     * @return The square root of the value.
     */
    int136_t sqrt(const int136_t& x);

    /**
     * Calculate the sine of an int value based on Taylor series expansion.
     * @param x The value to calculate the sine of.
     * @return The sine of the value.
     */
    int136_t sin(int136_t x);

    /**
     * Calculate the cosine of an int value based on sine and Pythagorean identity.
     * @param x The value to calculate the cosine of.
     * @return The cosine of the value.
     */
    int136_t cos(const int136_t& x);

    /**
     * Get the absolute value of an int.
     * @param x The value to get the absolute value of.
     * @return The absolute value of the value.
     */
    int136_t abs(const int136_t& x);

    /**
     * Add the internal values of two vectors.
     * @param u The first vector to add from.
     * @param v The second vector to add from.
     * @return A new vector with the resulting sum of both vectors.
     */
    Vector add(const Vector& u, const Vector& v);

    /**
     * Subtract the internal values of two vectors.
     * @param u The first vector to subtract from.
     * @param v The second vector to subtract from.
     * @return A new vector with the resulting subtraction of both vectors.
     */
    Vector sub(const Vector& u, const Vector& v);

    /**
     * Multiply the internal values of two vectors.
     * @param u The first vector to multiply from.
     * @param v The second vector to multiply from.
     * @return A new vector with the resulting multiplication of both vectors.
     */
    Vector mul(const Vector& u, const Vector& v);

    /**
     * Overload of mul() that takes an integer instead of a second vector.
     * @param v The vector to multiply from.
     * @param m The integer to multiply from.
     * @return A new vector with the resulting multiplication of the vector by the integer.
     */
    Vector mul(const Vector& v, const int136_t& m);

    /**
     * Divide the internal values of a vector by a given integer.
     * @param v The vector to divide from.
     * @param d The integer to divide from.
     * @return A new vector with the resulting division of the vector by the integer.
     */
    Vector div(const Vector& v, const int136_t& d);

    /**
     * Calculate the dot product between two vectors.
     * @param u The first vector to get the dot product from.
     * @param v The second vector to get the dot product from.
     * @return The dot product value as an integer.
     */
    int136_t dot(const Vector& u, const Vector& v);

    /**
     * Calculate the cross product between two vectors.
     * @param u The first vector to get the cross product from.
     * @param v The second vector to get the cross product from.
     * @return A new vector with the resulting cross product from both vectors.
     */
    Vector cross(const Vector& u, const Vector& v);

    /**
     * Calculate the normalization for a given vector.
     * @param v The vector to normalize.
     * @return A normalized copy of the vector.
     */
    Vector norm(const Vector& v);

    /**
     * Bound a vector's values to the allowed [0, 1] range.
     * @param v The vector to clamp.
     * @return A clamped copy of the vector.
     */
    Vector clamp(const Vector& v);

    /**
     * Calculate the intersection of a ray with a sphere.
     * @param s The sphere to intersect with.
     * @param r The ray to intersect with.
     * @return The distance until the first intersection point, or zero in case of no intersection.
     */
    int136_t intersect(const Sphere& s, const Ray& r);

    /**
     * Calculate the intersection of a ray with a triangle.
     * @param t The triangle to intersect with.
     * @param r The ray to intersect with.
     * @return The distance until the first intersection point, or zero in case of no intersection.
     */
    int136_t intersect(const Triangle& t, const Ray& r);

    /**
     * Calculate the radiance of a ray.
     * @param ray The ray to calculate the radiance from.
     * @return A vector representing the radiance.
     */
    Vector radiance(Ray& ray);

    /**
     * Overload of radiance() for spheres.
     * @param ray The ray to calculate the radiance from.
     * @param obj The Sphere object to use as base for calculation.
     * @param dist The distance between the ray and the object.
     * @return A vector representing the radiance.
     */
    Vector radiance(const Ray& ray, const Sphere& obj, const int136_t& dist);

    /**
     * Overload of radiance() for triangles.
     * @param ray The ray to calculate the radiance from.
     * @param obj The Triangle object to use as base for calculation.
     * @param dist The distance between the ray and the object.
     * @return A vector representing the radiance.
     */
    Vector radiance(const Ray& ray, const Triangle& obj, const int136_t& dist);

    /**
     * Calculate the diffusion of a ray.
     * @param ray The ray to calculate the diffusion from.
     * @param intersect A vector representing an intersection.
     * @param normal A vector representing the normal.
     * @return A vector representing the diffusion.
     */
    Vector diffuse(const Ray& ray, const Vector& intersect, const Vector& normal);

    /**
     * Calculate the specular reflection of a ray.
     * @param ray The ray to calculate the specular from.
     * @param intersect A vector representing an intersection.
     * @param normal A vector representing the normal.
     * @return A vector representing the specular.
     */
    Vector specular(const Ray& ray, const Vector& intersect, const Vector& normal);

    /**
     * Calculate the refractive reflection of a ray.
     * @param ray The ray to calculate the refractive from.
     * @param intersect A vector representing an intersection.
     * @param normal A vector representing the normal.
     * @param nnt TODO
     * @param ddn TODO
     * @param cos2t TODO
     * @return A vector representing the refractive.
     */
    Vector refractive(
      const Ray& ray, const Vector& intersect, const Vector& normal,
      const int136_t& nnt, const int136_t& ddn, const int136_t& cos2t
    );

    /**
     * Calculate the intersection of a ray with all the objects.
     * @param ray The ray to intersect.
     * @return The intersection of the ray with the closest object.
     */
    std::tuple<int136_t, Primitive, uint136_t> traceray(const Ray& ray);

    /// Register the contract structure.
    static void registerContract() {
      DynamicContract::registerContractMethods<
        SnailTracerOptimized, int136_t&, int136_t&,
        const Address&, const Address&, const uint136_t&, DB&
      >(
        std::vector<std::string>{"w", "h"},
        std::make_tuple("TracePixel", &SnailTracerOptimized::TracePixel, FunctionTypes::NonPayable, std::vector<std::string>{"x", "y", "spp"}),
        std::make_tuple("TraceScanline", &SnailTracerOptimized::TraceScanline, FunctionTypes::NonPayable, std::vector<std::string>{"y", "spp"}),
        std::make_tuple("TraceImage", &SnailTracerOptimized::TraceImage, FunctionTypes::NonPayable, std::vector<std::string>{"spp"}),
        std::make_tuple("Benchmark", &SnailTracerOptimized::Benchmark, FunctionTypes::NonPayable, std::vector<std::string>{}),
        std::make_tuple("trace", &SnailTracerOptimized::trace, FunctionTypes::NonPayable, std::vector<std::string>{"x", "y", "spp"}),
        std::make_tuple("rand", &SnailTracerOptimized::rand, FunctionTypes::NonPayable, std::vector<std::string>{}),
        std::make_tuple("clamp", static_cast<int136_t(SnailTracerOptimized::*)(const int136_t&)>(&SnailTracerOptimized::clamp), FunctionTypes::NonPayable, std::vector<std::string>{"x"}),
        std::make_tuple("sqrt", &SnailTracerOptimized::sqrt, FunctionTypes::NonPayable, std::vector<std::string>{"x"}),
        std::make_tuple("sin", &SnailTracerOptimized::sin, FunctionTypes::NonPayable, std::vector<std::string>{"x"}),
        std::make_tuple("cos", &SnailTracerOptimized::cos, FunctionTypes::NonPayable, std::vector<std::string>{"x"}),
        std::make_tuple("abs", &SnailTracerOptimized::abs, FunctionTypes::NonPayable, std::vector<std::string>{"x"}),
        std::make_tuple("add", &SnailTracerOptimized::add, FunctionTypes::NonPayable, std::vector<std::string>{"u", "v"}),
        std::make_tuple("sub", &SnailTracerOptimized::sub, FunctionTypes::NonPayable, std::vector<std::string>{"u", "v"}),
        std::make_tuple("mul", static_cast<Vector(SnailTracerOptimized::*)(const Vector&,const Vector&)>(&SnailTracerOptimized::mul), FunctionTypes::NonPayable, std::vector<std::string>{"u", "v"}),
        std::make_tuple("mul", static_cast<Vector(SnailTracerOptimized::*)(const Vector&,const int136_t&)>(&SnailTracerOptimized::mul), FunctionTypes::NonPayable, std::vector<std::string>{"v", "m"}),
        std::make_tuple("div", &SnailTracerOptimized::div, FunctionTypes::NonPayable, std::vector<std::string>{"v", "d"}),
        std::make_tuple("dot", &SnailTracerOptimized::dot, FunctionTypes::NonPayable, std::vector<std::string>{"u", "v"}),
        std::make_tuple("cross", &SnailTracerOptimized::cross, FunctionTypes::NonPayable, std::vector<std::string>{"u", "v"}),
        std::make_tuple("norm", &SnailTracerOptimized::norm, FunctionTypes::NonPayable, std::vector<std::string>{"v"}),
        std::make_tuple("clamp", static_cast<Vector(SnailTracerOptimized::*)(const Vector&)>(&SnailTracerOptimized::clamp), FunctionTypes::NonPayable, std::vector<std::string>{"v"}),
        std::make_tuple("intersect", static_cast<int136_t(SnailTracerOptimized::*)(const Sphere&, const Ray&)>(&SnailTracerOptimized::intersect), FunctionTypes::NonPayable, std::vector<std::string>{"s", "r"}),
        std::make_tuple("intersect", static_cast<int136_t(SnailTracerOptimized::*)(const Triangle&, const Ray&)>(&SnailTracerOptimized::intersect), FunctionTypes::NonPayable, std::vector<std::string>{"t", "r"}),
        std::make_tuple("radiance", static_cast<Vector(SnailTracerOptimized::*)(Ray&)>(&SnailTracerOptimized::radiance), FunctionTypes::NonPayable, std::vector<std::string>{"ray"}),
        std::make_tuple("radiance", static_cast<Vector(SnailTracerOptimized::*)(const Ray&, const Sphere&, const int136_t&)>(&SnailTracerOptimized::radiance), FunctionTypes::NonPayable, std::vector<std::string>{"ray", "obj", "dist"}),
        std::make_tuple("radiance", static_cast<Vector(SnailTracerOptimized::*)(const Ray&, const Triangle&, const int136_t&)>(&SnailTracerOptimized::radiance), FunctionTypes::NonPayable, std::vector<std::string>{"ray", "obj", "dist"}),
        std::make_tuple("diffuse", &SnailTracerOptimized::diffuse, FunctionTypes::NonPayable, std::vector<std::string>{"ray", "intersect", "normal"}),
        std::make_tuple("specular", &SnailTracerOptimized::specular, FunctionTypes::NonPayable, std::vector<std::string>{"ray", "intersect", "normal"}),
        std::make_tuple("refractive", &SnailTracerOptimized::refractive, FunctionTypes::NonPayable, std::vector<std::string>{"ray", "intersect", "normal", "nnt", "ddn", "cos2t"}),
        std::make_tuple("traceray", &SnailTracerOptimized::traceray, FunctionTypes::NonPayable, std::vector<std::string>{"ray"})
      );
    }

    DBBatch dump() const override; ///< Dump method.
};

#endif // SNAILTRACEROPTIMIZED_H
