#ifndef BDK_CONTRACT_COSTS_H
#define BDK_CONTRACT_COSTS_H

#include <cstdint>

constexpr uint64_t CONTRACT_EXECUTION_COST = 21'000;
constexpr uint64_t EVM_CONTRACT_CREATION_COST = 100'000;
constexpr uint64_t CPP_CONTRACT_CREATION_COST = 50'000;
constexpr uint64_t CPP_CONTRACT_CALL_COST = 1'000;
constexpr uint64_t EVM_CONTRACT_CALL_COST = 5'000; // NOT USED DUE TO NOT BEING COMPATIBLE WITH ETHEREUM STANDARD (YELLOW PAPER)

#endif // BDK_CONTRACT_COSTS_H
