#include "../../src/libs/json.hpp"

/// Typedef for json.
using json = nlohmann::ordered_json;


namespace EXPECTED
{
  namespace ERC20 {
    json transferFrom = json::parse("{\n"
                                    "        \"inputs\": [\n"
                                    "            {\n"
                                    "                \"internalType\": \"address\",\n"
                                    "                \"name\": \"from\",\n"
                                    "                \"type\": \"address\"\n"
                                    "            },\n"
                                    "            {\n"
                                    "                \"internalType\": \"address\",\n"
                                    "                \"name\": \"to\",\n"
                                    "                \"type\": \"address\"\n"
                                    "            },\n"
                                    "            {\n"
                                    "                \"internalType\": \"uint256\",\n"
                                    "                \"name\": \"value\",\n"
                                    "                \"type\": \"uint256\"\n"
                                    "            }\n"
                                    "        ],\n"
                                    "        \"name\": \"transferFrom\",\n"
                                    "        \"outputs\": [],\n"
                                    "        \"stateMutability\": \"nonpayable\",\n"
                                    "        \"type\": \"function\"\n"
                                    "    }");

    json approve = json::parse("{\n"
                               "        \"inputs\": [\n"
                               "            {\n"
                               "                \"internalType\": \"address\",\n"
                               "                \"name\": \"spender\",\n"
                               "                \"type\": \"address\"\n"
                               "            },\n"
                               "            {\n"
                               "                \"internalType\": \"uint256\",\n"
                               "                \"name\": \"value\",\n"
                               "                \"type\": \"uint256\"\n"
                               "            }\n"
                               "        ],\n"
                               "        \"name\": \"approve\",\n"
                               "        \"outputs\": [],\n"
                               "        \"stateMutability\": \"nonpayable\",\n"
                               "        \"type\": \"function\"\n"
                               "    }");

    json balanceOf = json::parse("{\n"
                                 "        \"inputs\": [\n"
                                 "            {\n"
                                 "                \"internalType\": \"address\",\n"
                                 "                \"name\": \"owner\",\n"
                                 "                \"type\": \"address\"\n"
                                 "            }\n"
                                 "        ],\n"
                                 "        \"name\": \"balanceOf\",\n"
                                 "        \"outputs\": [\n"
                                 "            {\n"
                                 "                \"internalType\": \"uint256\",\n"
                                 "                \"name\": \"\",\n"
                                 "                \"type\": \"uint256\"\n"
                                 "            }\n"
                                 "        ],\n"
                                 "        \"stateMutability\": \"view\",\n"
                                 "        \"type\": \"function\"\n"
                                 "    }");

    json totalSupply = json::parse("    {\n"
                                   "        \"inputs\": [],\n"
                                   "        \"name\": \"totalSupply\",\n"
                                   "        \"outputs\": [\n"
                                   "            {\n"
                                   "                \"internalType\": \"uint256\",\n"
                                   "                \"name\": \"\",\n"
                                   "                \"type\": \"uint256\"\n"
                                   "            }\n"
                                   "        ],\n"
                                   "        \"stateMutability\": \"view\",\n"
                                   "        \"type\": \"function\"\n"
                                   "    }");

    json transfer = json::parse("    {\n"
                                "        \"inputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"address\",\n"
                                "                \"name\": \"to\",\n"
                                "                \"type\": \"address\"\n"
                                "            },\n"
                                "            {\n"
                                "                \"internalType\": \"uint256\",\n"
                                "                \"name\": \"value\",\n"
                                "                \"type\": \"uint256\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"name\": \"transfer\",\n"
                                "        \"outputs\": [],\n"
                                "        \"stateMutability\": \"nonpayable\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json decimals = json::parse("    {\n"
                                "        \"inputs\": [],\n"
                                "        \"name\": \"decimals\",\n"
                                "        \"outputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"uint8\",\n"
                                "                \"name\": \"\",\n"
                                "                \"type\": \"uint8\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"stateMutability\": \"view\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json symbol = json::parse("    {\n"
                              "        \"inputs\": [],\n"
                              "        \"name\": \"symbol\",\n"
                              "        \"outputs\": [\n"
                              "            {\n"
                              "                \"internalType\": \"string\",\n"
                              "                \"name\": \"\",\n"
                              "                \"type\": \"string\"\n"
                              "            }\n"
                              "        ],\n"
                              "        \"stateMutability\": \"view\",\n"
                              "        \"type\": \"function\"\n"
                              "    }");

    json allowance = json::parse("    {\n"
                                 "        \"inputs\": [\n"
                                 "            {\n"
                                 "                \"internalType\": \"address\",\n"
                                 "                \"name\": \"owner\",\n"
                                 "                \"type\": \"address\"\n"
                                 "            },\n"
                                 "            {\n"
                                 "                \"internalType\": \"address\",\n"
                                 "                \"name\": \"spender\",\n"
                                 "                \"type\": \"address\"\n"
                                 "            }\n"
                                 "        ],\n"
                                 "        \"name\": \"allowance\",\n"
                                 "        \"outputs\": [\n"
                                 "            {\n"
                                 "                \"internalType\": \"uint256\",\n"
                                 "                \"name\": \"\",\n"
                                 "                \"type\": \"uint256\"\n"
                                 "            }\n"
                                 "        ],\n"
                                 "        \"stateMutability\": \"view\",\n"
                                 "        \"type\": \"function\"\n"
                                 "    }");

    json name = json::parse("    {\n"
                            "        \"inputs\": [],\n"
                            "        \"name\": \"name\",\n"
                            "        \"outputs\": [\n"
                            "            {\n"
                            "                \"internalType\": \"string\",\n"
                            "                \"name\": \"\",\n"
                            "                \"type\": \"string\"\n"
                            "            }\n"
                            "        ],\n"
                            "        \"stateMutability\": \"view\",\n"
                            "        \"type\": \"function\"\n"
                            "    }");
  }

  namespace ERC20Wrapper {
    json deposit = json::parse("    {\n"
                               "        \"inputs\": [\n"
                               "            {\n"
                               "                \"internalType\": \"address\",\n"
                               "                \"name\": \"token\",\n"
                               "                \"type\": \"address\"\n"
                               "            },\n"
                               "            {\n"
                               "                \"internalType\": \"uint256\",\n"
                               "                \"name\": \"value\",\n"
                               "                \"type\": \"uint256\"\n"
                               "            }\n"
                               "        ],\n"
                               "        \"name\": \"deposit\",\n"
                               "        \"outputs\": [],\n"
                               "        \"stateMutability\": \"nonpayable\",\n"
                               "        \"type\": \"function\"\n"
                               "    }");

    json transferTo = json::parse("    {\n"
                                  "        \"inputs\": [\n"
                                  "            {\n"
                                  "                \"internalType\": \"address\",\n"
                                  "                \"name\": \"token\",\n"
                                  "                \"type\": \"address\"\n"
                                  "            },\n"
                                  "            {\n"
                                  "                \"internalType\": \"address\",\n"
                                  "                \"name\": \"to\",\n"
                                  "                \"type\": \"address\"\n"
                                  "            },\n"
                                  "            {\n"
                                  "                \"internalType\": \"uint256\",\n"
                                  "                \"name\": \"value\",\n"
                                  "                \"type\": \"uint256\"\n"
                                  "            }\n"
                                  "        ],\n"
                                  "        \"name\": \"transferTo\",\n"
                                  "        \"outputs\": [],\n"
                                  "        \"stateMutability\": \"nonpayable\",\n"
                                  "        \"type\": \"function\"\n"
                                  "    }");

    json withdraw = json::parse("    {\n"
                                "        \"inputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"address\",\n"
                                "                \"name\": \"token\",\n"
                                "                \"type\": \"address\"\n"
                                "            },\n"
                                "            {\n"
                                "                \"internalType\": \"uint256\",\n"
                                "                \"name\": \"value\",\n"
                                "                \"type\": \"uint256\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"name\": \"withdraw\",\n"
                                "        \"outputs\": [],\n"
                                "        \"stateMutability\": \"nonpayable\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json getUserBalance = json::parse("{\n"
                                      "        \"inputs\": [\n"
                                      "            {\n"
                                      "                \"internalType\": \"address\",\n"
                                      "                \"name\": \"token\",\n"
                                      "                \"type\": \"address\"\n"
                                      "            },\n"
                                      "            {\n"
                                      "                \"internalType\": \"address\",\n"
                                      "                \"name\": \"user\",\n"
                                      "                \"type\": \"address\"\n"
                                      "            }\n"
                                      "        ],\n"
                                      "        \"name\": \"getUserBalance\",\n"
                                      "        \"outputs\": [\n"
                                      "            {\n"
                                      "                \"internalType\": \"uint256\",\n"
                                      "                \"name\": \"\",\n"
                                      "                \"type\": \"uint256\"\n"
                                      "            }\n"
                                      "        ],\n"
                                      "        \"stateMutability\": \"view\",\n"
                                      "        \"type\": \"function\"\n"
                                      "    }");

    json getContractBalance = json::parse("    {\n"
                                          "        \"inputs\": [\n"
                                          "            {\n"
                                          "                \"internalType\": \"address\",\n"
                                          "                \"name\": \"token\",\n"
                                          "                \"type\": \"address\"\n"
                                          "            }\n"
                                          "        ],\n"
                                          "        \"name\": \"getContractBalance\",\n"
                                          "        \"outputs\": [\n"
                                          "            {\n"
                                          "                \"internalType\": \"uint256\",\n"
                                          "                \"name\": \"\",\n"
                                          "                \"type\": \"uint256\"\n"
                                          "            }\n"
                                          "        ],\n"
                                          "        \"stateMutability\": \"view\",\n"
                                          "        \"type\": \"function\"\n"
                                          "    }");
  }

  namespace NativeWrapper {
    json withdraw = json::parse("    {\n"
                                "        \"inputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"uint256\",\n"
                                "                \"name\": \"value\",\n"
                                "                \"type\": \"uint256\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"name\": \"withdraw\",\n"
                                "        \"outputs\": [],\n"
                                "        \"stateMutability\": \"payable\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json deposit = json::parse("    {\n"
                               "        \"inputs\": [],\n"
                               "        \"name\": \"deposit\",\n"
                               "        \"outputs\": [],\n"
                               "        \"stateMutability\": \"payable\",\n"
                               "        \"type\": \"function\"\n"
                               "    }");
  }

  namespace ContractManager {
    json createNewERC20Contract = json::parse("{\n"
                                              "        \"inputs\": [\n"
                                              "            {\n"
                                              "                \"internalType\": \"string\",\n"
                                              "                \"name\": \"erc20name\",\n"
                                              "                \"type\": \"string\"\n"
                                              "            },\n"
                                              "            {\n"
                                              "                \"internalType\": \"string\",\n"
                                              "                \"name\": \"erc20symbol\",\n"
                                              "                \"type\": \"string\"\n"
                                              "            },\n"
                                              "            {\n"
                                              "                \"internalType\": \"uint8\",\n"
                                              "                \"name\": \"erc20decimals\",\n"
                                              "                \"type\": \"uint8\"\n"
                                              "            },\n"
                                              "            {\n"
                                              "                \"internalType\": \"uint256\",\n"
                                              "                \"name\": \"mintValue\",\n"
                                              "                \"type\": \"uint256\"\n"
                                              "            }\n"
                                              "        ],\n"
                                              "        \"name\": \"createNewERC20Contract\",\n"
                                              "        \"outputs\": [],\n"
                                              "        \"stateMutability\": \"nonpayable\",\n"
                                              "        \"type\": \"function\"\n"
                                              "    }");

    json createNewERC20WrapperContract = json::parse("    {\n"
                                                     "        \"inputs\": [],\n"
                                                     "        \"name\": \"createNewERC20WrapperContract\",\n"
                                                     "        \"outputs\": [],\n"
                                                     "        \"stateMutability\": \"nonpayable\",\n"
                                                     "        \"type\": \"function\"\n"
                                                     "    }");

    json createNewNativeWrapperContract = json::parse("{\n"
                                                      "        \"inputs\": [\n"
                                                      "            {\n"
                                                      "                \"internalType\": \"string\",\n"
                                                      "                \"name\": \"erc20_name\",\n"
                                                      "                \"type\": \"string\"\n"
                                                      "            },\n"
                                                      "            {\n"
                                                      "                \"internalType\": \"string\",\n"
                                                      "                \"name\": \"erc20_symbol\",\n"
                                                      "                \"type\": \"string\"\n"
                                                      "            },\n"
                                                      "            {\n"
                                                      "                \"internalType\": \"uint8\",\n"
                                                      "                \"name\": \"erc20_decimals\",\n"
                                                      "                \"type\": \"uint8\"\n"
                                                      "            }\n"
                                                      "        ],\n"
                                                      "        \"name\": \"createNewNativeWrapperContract\",\n"
                                                      "        \"outputs\": [],\n"
                                                      "        \"stateMutability\": \"nonpayable\",\n"
                                                      "        \"type\": \"function\"\n"
                                                      "    }");

    json createNewSimpleContract = json::parse("    {\n"
                                               "        \"inputs\": [\n"
                                               "            {\n"
                                               "                \"internalType\": \"string\",\n"
                                               "                \"name\": \"name_\",\n"
                                               "                \"type\": \"string\"\n"
                                               "            },\n"
                                               "            {\n"
                                               "                \"internalType\": \"uint256\",\n"
                                               "                \"name\": \"value_\",\n"
                                               "                \"type\": \"uint256\"\n"
                                               "            }\n"
                                               "        ],\n"
                                               "        \"name\": \"createNewSimpleContractContract\",\n"
                                               "        \"outputs\": [],\n"
                                               "        \"stateMutability\": \"nonpayable\",\n"
                                               "        \"type\": \"function\"\n"
                                               "    }");

    json createNewDEXV2PairContract = json::parse("    {\n"
                                                  "        \"inputs\": [],\n"
                                                  "        \"name\": \"createNewDEXV2PairContract\",\n"
                                                  "        \"outputs\": [],\n"
                                                  "        \"stateMutability\": \"nonpayable\",\n"
                                                  "        \"type\": \"function\"\n"
                                                  "    }");

    json createNewDEXV2FactoryContract = json::parse("    {\n"
                                                     "        \"inputs\": [\n"
                                                     "            {\n"
                                                     "                \"internalType\": \"address\",\n"
                                                     "                \"name\": \"_feeToSetter\",\n"
                                                     "                \"type\": \"address\"\n"
                                                     "            }\n"
                                                     "        ],\n"
                                                     "        \"name\": \"createNewDEXV2FactoryContract\",\n"
                                                     "        \"outputs\": [],\n"
                                                     "        \"stateMutability\": \"nonpayable\",\n"
                                                     "        \"type\": \"function\"\n"
                                                     "    }");

    json createNewDEXV2Router02Contract = json::parse("    {\n"
                                                      "        \"inputs\": [\n"
                                                      "            {\n"
                                                      "                \"internalType\": \"address\",\n"
                                                      "                \"name\": \"factory\",\n"
                                                      "                \"type\": \"address\"\n"
                                                      "            },\n"
                                                      "            {\n"
                                                      "                \"internalType\": \"address\",\n"
                                                      "                \"name\": \"wrappedNative\",\n"
                                                      "                \"type\": \"address\"\n"
                                                      "            }\n"
                                                      "        ],\n"
                                                      "        \"name\": \"createNewDEXV2Router02Contract\",\n"
                                                      "        \"outputs\": [],\n"
                                                      "        \"stateMutability\": \"nonpayable\",\n"
                                                      "        \"type\": \"function\"\n"
                                                      "    }");

    json createNewERC721Contract = json::parse("{\n"
                                               "        \"inputs\": [\n"
                                               "            {\n"
                                               "                \"internalType\": \"string\",\n"
                                               "                \"name\": \"erc721name\",\n"
                                               "                \"type\": \"string\"\n"
                                               "            },\n"
                                               "            {\n"
                                               "                \"internalType\": \"string\",\n"
                                               "                \"name\": \"erc721symbol\",\n"
                                               "                \"type\": \"string\"\n"
                                               "            }\n"
                                               "        ],\n"
                                               "        \"name\": \"createNewERC721Contract\",\n"
                                               "        \"outputs\": [],\n"
                                               "        \"stateMutability\": \"nonpayable\",\n"
                                               "        \"type\": \"function\"\n"
                                               "    }");

    json createNewThrowTestAContract = json::parse("    {\n"
                                                   "        \"inputs\": [],\n"
                                                   "        \"name\": \"createNewThrowTestAContract\",\n"
                                                   "        \"outputs\": [],\n"
                                                   "        \"stateMutability\": \"nonpayable\",\n"
                                                   "        \"type\": \"function\"\n"
                                                   "    }");

    json createNewThrowTestBContract = json::parse("    {\n"
                                                   "        \"inputs\": [],\n"
                                                   "        \"name\": \"createNewThrowTestBContract\",\n"
                                                   "        \"outputs\": [],\n"
                                                   "        \"stateMutability\": \"nonpayable\",\n"
                                                   "        \"type\": \"function\"\n"
                                                   "    }");

    json createNewThrowTestCContract = json::parse("    {\n"
                                                   "        \"inputs\": [],\n"
                                                   "        \"name\": \"createNewThrowTestCContract\",\n"
                                                   "        \"outputs\": [],\n"
                                                   "        \"stateMutability\": \"nonpayable\",\n"
                                                   "        \"type\": \"function\"\n"
                                                   "    }");

    json getDeployedContracts = json::parse("    {\n"
                                            "        \"inputs\": [],\n"
                                            "        \"name\": \"getDeployedContracts\",\n"
                                            "        \"outputs\": [\n"
                                            "            {\n"
                                            "                \"internalType\": \"string[]\",\n"
                                            "                \"name\": \"\",\n"
                                            "                \"type\": \"string[]\"\n"
                                            "            },\n"
                                            "            {\n"
                                            "                \"internalType\": \"address[]\",\n"
                                            "                \"name\": \"\",\n"
                                            "                \"type\": \"address[]\"\n"
                                            "            }\n"
                                            "        ],\n"
                                            "        \"stateMutability\": \"view\",\n"
                                            "        \"type\": \"function\"\n"
                                            "    }");
  }

  namespace SimpleContract {
    json getNamesAndValuesInArrayOfArrays = json::parse("  {\n"
                                                        "    \"inputs\": [\n"
                                                        "      {\n"
                                                        "        \"internalType\": \"uint256\",\n"
                                                        "        \"name\": \"i\",\n"
                                                        "        \"type\": \"uint256\"\n"
                                                        "      }\n"
                                                        "    ],\n"
                                                        "    \"name\": \"getNamesAndValuesInArrayOfArrays\",\n"
                                                        "    \"outputs\": [\n"
                                                        "      {\n"
                                                        "        \"components\": [\n"
                                                        "          {\n"
                                                        "            \"internalType\": \"string\",\n"
                                                        "            \"type\": \"string\"\n"
                                                        "          },\n"
                                                        "          {\n"
                                                        "            \"internalType\": \"uint256\",\n"
                                                        "            \"type\": \"uint256\"\n"
                                                        "          }\n"
                                                        "        ],\n"
                                                        "        \"type\": \"tuple[][]\"\n"
                                                        "      }\n"
                                                        "    ],\n"
                                                        "    \"stateMutability\": \"view\",\n"
                                                        "    \"type\": \"function\"\n"
                                                        "  }");

    json getNamesAndValuesInTuple = json::parse("    {\n"
                                                "        \"inputs\": [\n"
                                                "            {\n"
                                                "                \"internalType\": \"uint256\",\n"
                                                "                \"name\": \"i\",\n"
                                                "                \"type\": \"uint256\"\n"
                                                "            }\n"
                                                "        ],\n"
                                                "        \"name\": \"getNamesAndValuesInTuple\",\n"
                                                "        \"outputs\": [\n"
                                                "            {\n"
                                                "                \"components\": [\n"
                                                "                    {\n"
                                                "                        \"internalType\": \"string\",\n"
                                                "                        \"type\": \"string\"\n"
                                                "                    },\n"
                                                "                    {\n"
                                                "                        \"internalType\": \"uint256\",\n"
                                                "                        \"type\": \"uint256\"\n"
                                                "                    }\n"
                                                "                ],\n"
                                                "                \"type\": \"tuple[]\"\n"
                                                "            }\n"
                                                "        ],\n"
                                                "        \"stateMutability\": \"view\",\n"
                                                "        \"type\": \"function\"\n"
                                                "    }");

    json getNameAndValue = json::parse("    {\n"
                                       "        \"inputs\": [],\n"
                                       "        \"name\": \"getNameAndValue\",\n"
                                       "        \"outputs\": [\n"
                                       "            {\n"
                                       "                \"components\": [\n"
                                       "                    {\n"
                                       "                        \"internalType\": \"string\",\n"
                                       "                        \"type\": \"string\"\n"
                                       "                    },\n"
                                       "                    {\n"
                                       "                        \"internalType\": \"uint256\",\n"
                                       "                        \"type\": \"uint256\"\n"
                                       "                    }\n"
                                       "                ],\n"
                                       "                \"type\": \"tuple\"\n"
                                       "            }\n"
                                       "        ],\n"
                                       "        \"stateMutability\": \"view\",\n"
                                       "        \"type\": \"function\"\n"
                                       "    }");

    json getValues = json::parse("    {\n"
                                 "        \"inputs\": [\n"
                                 "            {\n"
                                 "                \"internalType\": \"uint256\",\n"
                                 "                \"name\": \"i\",\n"
                                 "                \"type\": \"uint256\"\n"
                                 "            }\n"
                                 "        ],\n"
                                 "        \"name\": \"getValues\",\n"
                                 "        \"outputs\": [\n"
                                 "            {\n"
                                 "                \"internalType\": \"uint256[]\",\n"
                                 "                \"name\": \"\",\n"
                                 "                \"type\": \"uint256[]\"\n"
                                 "            }\n"
                                 "        ],\n"
                                 "        \"stateMutability\": \"view\",\n"
                                 "        \"type\": \"function\"\n"
                                 "    }");

    json getValue = json::parse("    {\n"
                                "        \"inputs\": [],\n"
                                "        \"name\": \"getValue\",\n"
                                "        \"outputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"uint256\",\n"
                                "                \"name\": \"\",\n"
                                "                \"type\": \"uint256\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"stateMutability\": \"view\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json getName = json::parse("    {\n"
                               "        \"inputs\": [],\n"
                               "        \"name\": \"getName\",\n"
                               "        \"outputs\": [\n"
                               "            {\n"
                               "                \"internalType\": \"string\",\n"
                               "                \"name\": \"\",\n"
                               "                \"type\": \"string\"\n"
                               "            }\n"
                               "        ],\n"
                               "        \"stateMutability\": \"view\",\n"
                               "        \"type\": \"function\"\n"
                               "    }");

    json setNamesAndValuesInArrayOfArrays = json::parse("  {\n"
                                                        "    \"inputs\": [\n"
                                                        "      {\n"
                                                        "        \"components\": [\n"
                                                        "          {\n"
                                                        "            \"internalType\": \"string\",\n"
                                                        "            \"type\": \"string\"\n"
                                                        "          },\n"
                                                        "          {\n"
                                                        "            \"internalType\": \"uint256\",\n"
                                                        "            \"type\": \"uint256\"\n"
                                                        "          }\n"
                                                        "        ],\n"
                                                        "        \"name\": \"argNameAndValue\",\n"
                                                        "        \"type\": \"tuple[][]\"\n"
                                                        "      }\n"
                                                        "    ],\n"
                                                        "    \"name\": \"setNamesAndValuesInArrayOfArrays\",\n"
                                                        "    \"outputs\": [],\n"
                                                        "    \"stateMutability\": \"nonpayable\",\n"
                                                        "    \"type\": \"function\"\n"
                                                        "  }");

    json setNamesAndValuesInTuple = json::parse("    {\n"
                                                "        \"inputs\": [\n"
                                                "            {\n"
                                                "                \"components\": [\n"
                                                "                    {\n"
                                                "                        \"internalType\": \"string\",\n"
                                                "                        \"type\": \"string\"\n"
                                                "                    },\n"
                                                "                    {\n"
                                                "                        \"internalType\": \"uint256\",\n"
                                                "                        \"type\": \"uint256\"\n"
                                                "                    }\n"
                                                "                ],\n"
                                                "                \"name\": \"argNameAndValue\",\n"
                                                "                \"type\": \"tuple[]\"\n"
                                                "            }\n"
                                                "        ],\n"
                                                "        \"name\": \"setNamesAndValuesInTuple\",\n"
                                                "        \"outputs\": [],\n"
                                                "        \"stateMutability\": \"nonpayable\",\n"
                                                "        \"type\": \"function\"\n"
                                                "    }");

    json getNames = json::parse("    {\n"
                                "        \"inputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"uint256\",\n"
                                "                \"name\": \"i\",\n"
                                "                \"type\": \"uint256\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"name\": \"getNames\",\n"
                                "        \"outputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"string[]\",\n"
                                "                \"name\": \"\",\n"
                                "                \"type\": \"string[]\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"stateMutability\": \"view\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json setValues = json::parse("    {\n"
                                 "        \"inputs\": [\n"
                                 "            {\n"
                                 "                \"internalType\": \"uint256[]\",\n"
                                 "                \"name\": \"argValue\",\n"
                                 "                \"type\": \"uint256[]\"\n"
                                 "            }\n"
                                 "        ],\n"
                                 "        \"name\": \"setValues\",\n"
                                 "        \"outputs\": [],\n"
                                 "        \"stateMutability\": \"nonpayable\",\n"
                                 "        \"type\": \"function\"\n"
                                 "    }");

    json setValue = json::parse("    {\n"
                                "        \"inputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"uint256\",\n"
                                "                \"name\": \"argValue\",\n"
                                "                \"type\": \"uint256\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"name\": \"setValue\",\n"
                                "        \"outputs\": [],\n"
                                "        \"stateMutability\": \"nonpayable\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json setNamesAndValues = json::parse("    {\n"
                                         "        \"inputs\": [\n"
                                         "            {\n"
                                         "                \"internalType\": \"string[]\",\n"
                                         "                \"name\": \"argName\",\n"
                                         "                \"type\": \"string[]\"\n"
                                         "            },\n"
                                         "            {\n"
                                         "                \"internalType\": \"uint256[]\",\n"
                                         "                \"name\": \"argValue\",\n"
                                         "                \"type\": \"uint256[]\"\n"
                                         "            }\n"
                                         "        ],\n"
                                         "        \"name\": \"setNamesAndValues\",\n"
                                         "        \"outputs\": [],\n"
                                         "        \"stateMutability\": \"nonpayable\",\n"
                                         "        \"type\": \"function\"\n"
                                         "    }");

    json setNames = json::parse("    {\n"
                                "        \"inputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"string[]\",\n"
                                "                \"name\": \"argName\",\n"
                                "                \"type\": \"string[]\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"name\": \"setNames\",\n"
                                "        \"outputs\": [],\n"
                                "        \"stateMutability\": \"nonpayable\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json getNamesAndValues = json::parse("{\n"
                                         "        \"inputs\": [\n"
                                         "            {\n"
                                         "                \"internalType\": \"uint256\",\n"
                                         "                \"name\": \"i\",\n"
                                         "                \"type\": \"uint256\"\n"
                                         "            }\n"
                                         "        ],\n"
                                         "        \"name\": \"getNamesAndValues\",\n"
                                         "        \"outputs\": [\n"
                                         "            {\n"
                                         "                \"components\": [\n"
                                         "                    {\n"
                                         "                        \"internalType\": \"string[]\",\n"
                                         "                        \"type\": \"string[]\"\n"
                                         "                    },\n"
                                         "                    {\n"
                                         "                        \"internalType\": \"uint256[]\",\n"
                                         "                        \"type\": \"uint256[]\"\n"
                                         "                    }\n"
                                         "                ],\n"
                                         "                \"type\": \"tuple\"\n"
                                         "            }\n"
                                         "        ],\n"
                                         "        \"stateMutability\": \"view\",\n"
                                         "        \"type\": \"function\"\n"
                                         "    }");

    json setName = json::parse("    {\n"
                               "        \"inputs\": [\n"
                               "            {\n"
                               "                \"internalType\": \"string\",\n"
                               "                \"name\": \"argName\",\n"
                               "                \"type\": \"string\"\n"
                               "            }\n"
                               "        ],\n"
                               "        \"name\": \"setName\",\n"
                               "        \"outputs\": [],\n"
                               "        \"stateMutability\": \"nonpayable\",\n"
                               "        \"type\": \"function\"\n"
                               "    }");

    json getValueOverload = json::parse("{\n"
                                        "    \"inputs\": [\n"
                                        "      {\n"
                                        "        \"internalType\": \"uint256\",\n"
                                        "        \"name\": \"\",\n"
                                        "        \"type\": \"uint256\"\n"
                                        "      }\n"
                                        "    ],\n"
                                        "    \"name\": \"getValue\",\n"
                                        "    \"outputs\": [\n"
                                        "      {\n"
                                        "        \"internalType\": \"uint256\",\n"
                                        "        \"name\": \"\",\n"
                                        "        \"type\": \"uint256\"\n"
                                        "      }\n"
                                        "    ],\n"
                                        "    \"stateMutability\": \"view\",\n"
                                        "    \"type\": \"function\"\n"
                                        "  }");
  }
}