/*
Copyright (c) [2023-2024] [Sparq Network]

This software is distributed under the MIT License.
See the LICENSE.txt file in the project root for more information.
*/

#include "../../src/libs/json.hpp"

/// Typedef for json.
using json = nlohmann::ordered_json;

// TODO: redo this but better organized
namespace EXPECTED
{
  namespace ERC20 {
    json transferFrom = json::parse("{\n"
                                    "        \"inputs\": [\n"
                                    "            {\n"
                                    "                \"internalType\": \"address\",\n"
                                    "                \"name\": \"from\",\n"
                                    "                \"type\": \"address\"\n"
                                    "            },\n"
                                    "            {\n"
                                    "                \"internalType\": \"address\",\n"
                                    "                \"name\": \"to\",\n"
                                    "                \"type\": \"address\"\n"
                                    "            },\n"
                                    "            {\n"
                                    "                \"internalType\": \"uint256\",\n"
                                    "                \"name\": \"value\",\n"
                                    "                \"type\": \"uint256\"\n"
                                    "            }\n"
                                    "        ],\n"
                                    "        \"name\": \"transferFrom\",\n"
                                    "        \"outputs\": [],\n"
                                    "        \"stateMutability\": \"nonpayable\",\n"
                                    "        \"type\": \"function\"\n"
                                    "    }");

    json approve = json::parse("{\n"
                               "        \"inputs\": [\n"
                               "            {\n"
                               "                \"internalType\": \"address\",\n"
                               "                \"name\": \"spender\",\n"
                               "                \"type\": \"address\"\n"
                               "            },\n"
                               "            {\n"
                               "                \"internalType\": \"uint256\",\n"
                               "                \"name\": \"value\",\n"
                               "                \"type\": \"uint256\"\n"
                               "            }\n"
                               "        ],\n"
                               "        \"name\": \"approve\",\n"
                               "        \"outputs\": [],\n"
                               "        \"stateMutability\": \"nonpayable\",\n"
                               "        \"type\": \"function\"\n"
                               "    }");

    json balanceOf = json::parse("{\n"
                                 "        \"inputs\": [\n"
                                 "            {\n"
                                 "                \"internalType\": \"address\",\n"
                                 "                \"name\": \"owner\",\n"
                                 "                \"type\": \"address\"\n"
                                 "            }\n"
                                 "        ],\n"
                                 "        \"name\": \"balanceOf\",\n"
                                 "        \"outputs\": [\n"
                                 "            {\n"
                                 "                \"internalType\": \"uint256\",\n"
                                 "                \"name\": \"\",\n"
                                 "                \"type\": \"uint256\"\n"
                                 "            }\n"
                                 "        ],\n"
                                 "        \"stateMutability\": \"view\",\n"
                                 "        \"type\": \"function\"\n"
                                 "    }");

    json totalSupply = json::parse("    {\n"
                                   "        \"inputs\": [],\n"
                                   "        \"name\": \"totalSupply\",\n"
                                   "        \"outputs\": [\n"
                                   "            {\n"
                                   "                \"internalType\": \"uint256\",\n"
                                   "                \"name\": \"\",\n"
                                   "                \"type\": \"uint256\"\n"
                                   "            }\n"
                                   "        ],\n"
                                   "        \"stateMutability\": \"view\",\n"
                                   "        \"type\": \"function\"\n"
                                   "    }");

    json transfer = json::parse("    {\n"
                                "        \"inputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"address\",\n"
                                "                \"name\": \"to\",\n"
                                "                \"type\": \"address\"\n"
                                "            },\n"
                                "            {\n"
                                "                \"internalType\": \"uint256\",\n"
                                "                \"name\": \"value\",\n"
                                "                \"type\": \"uint256\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"name\": \"transfer\",\n"
                                "        \"outputs\": [],\n"
                                "        \"stateMutability\": \"nonpayable\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json decimals = json::parse("    {\n"
                                "        \"inputs\": [],\n"
                                "        \"name\": \"decimals\",\n"
                                "        \"outputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"uint8\",\n"
                                "                \"name\": \"\",\n"
                                "                \"type\": \"uint8\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"stateMutability\": \"view\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json symbol = json::parse("    {\n"
                              "        \"inputs\": [],\n"
                              "        \"name\": \"symbol\",\n"
                              "        \"outputs\": [\n"
                              "            {\n"
                              "                \"internalType\": \"string\",\n"
                              "                \"name\": \"\",\n"
                              "                \"type\": \"string\"\n"
                              "            }\n"
                              "        ],\n"
                              "        \"stateMutability\": \"view\",\n"
                              "        \"type\": \"function\"\n"
                              "    }");

    json allowance = json::parse("    {\n"
                                 "        \"inputs\": [\n"
                                 "            {\n"
                                 "                \"internalType\": \"address\",\n"
                                 "                \"name\": \"owner\",\n"
                                 "                \"type\": \"address\"\n"
                                 "            },\n"
                                 "            {\n"
                                 "                \"internalType\": \"address\",\n"
                                 "                \"name\": \"spender\",\n"
                                 "                \"type\": \"address\"\n"
                                 "            }\n"
                                 "        ],\n"
                                 "        \"name\": \"allowance\",\n"
                                 "        \"outputs\": [\n"
                                 "            {\n"
                                 "                \"internalType\": \"uint256\",\n"
                                 "                \"name\": \"\",\n"
                                 "                \"type\": \"uint256\"\n"
                                 "            }\n"
                                 "        ],\n"
                                 "        \"stateMutability\": \"view\",\n"
                                 "        \"type\": \"function\"\n"
                                 "    }");

    json name = json::parse("    {\n"
                            "        \"inputs\": [],\n"
                            "        \"name\": \"name\",\n"
                            "        \"outputs\": [\n"
                            "            {\n"
                            "                \"internalType\": \"string\",\n"
                            "                \"name\": \"\",\n"
                            "                \"type\": \"string\"\n"
                            "            }\n"
                            "        ],\n"
                            "        \"stateMutability\": \"view\",\n"
                            "        \"type\": \"function\"\n"
                            "    }");
  }

  namespace ERC20Wrapper {
    json deposit = json::parse("    {\n"
                               "        \"inputs\": [\n"
                               "            {\n"
                               "                \"internalType\": \"address\",\n"
                               "                \"name\": \"token\",\n"
                               "                \"type\": \"address\"\n"
                               "            },\n"
                               "            {\n"
                               "                \"internalType\": \"uint256\",\n"
                               "                \"name\": \"value\",\n"
                               "                \"type\": \"uint256\"\n"
                               "            }\n"
                               "        ],\n"
                               "        \"name\": \"deposit\",\n"
                               "        \"outputs\": [],\n"
                               "        \"stateMutability\": \"nonpayable\",\n"
                               "        \"type\": \"function\"\n"
                               "    }");

    json transferTo = json::parse("    {\n"
                                  "        \"inputs\": [\n"
                                  "            {\n"
                                  "                \"internalType\": \"address\",\n"
                                  "                \"name\": \"token\",\n"
                                  "                \"type\": \"address\"\n"
                                  "            },\n"
                                  "            {\n"
                                  "                \"internalType\": \"address\",\n"
                                  "                \"name\": \"to\",\n"
                                  "                \"type\": \"address\"\n"
                                  "            },\n"
                                  "            {\n"
                                  "                \"internalType\": \"uint256\",\n"
                                  "                \"name\": \"value\",\n"
                                  "                \"type\": \"uint256\"\n"
                                  "            }\n"
                                  "        ],\n"
                                  "        \"name\": \"transferTo\",\n"
                                  "        \"outputs\": [],\n"
                                  "        \"stateMutability\": \"nonpayable\",\n"
                                  "        \"type\": \"function\"\n"
                                  "    }");

    json withdraw = json::parse("    {\n"
                                "        \"inputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"address\",\n"
                                "                \"name\": \"token\",\n"
                                "                \"type\": \"address\"\n"
                                "            },\n"
                                "            {\n"
                                "                \"internalType\": \"uint256\",\n"
                                "                \"name\": \"value\",\n"
                                "                \"type\": \"uint256\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"name\": \"withdraw\",\n"
                                "        \"outputs\": [],\n"
                                "        \"stateMutability\": \"nonpayable\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json getUserBalance = json::parse("{\n"
                                      "        \"inputs\": [\n"
                                      "            {\n"
                                      "                \"internalType\": \"address\",\n"
                                      "                \"name\": \"token\",\n"
                                      "                \"type\": \"address\"\n"
                                      "            },\n"
                                      "            {\n"
                                      "                \"internalType\": \"address\",\n"
                                      "                \"name\": \"user\",\n"
                                      "                \"type\": \"address\"\n"
                                      "            }\n"
                                      "        ],\n"
                                      "        \"name\": \"getUserBalance\",\n"
                                      "        \"outputs\": [\n"
                                      "            {\n"
                                      "                \"internalType\": \"uint256\",\n"
                                      "                \"name\": \"\",\n"
                                      "                \"type\": \"uint256\"\n"
                                      "            }\n"
                                      "        ],\n"
                                      "        \"stateMutability\": \"view\",\n"
                                      "        \"type\": \"function\"\n"
                                      "    }");

    json getContractBalance = json::parse("    {\n"
                                          "        \"inputs\": [\n"
                                          "            {\n"
                                          "                \"internalType\": \"address\",\n"
                                          "                \"name\": \"token\",\n"
                                          "                \"type\": \"address\"\n"
                                          "            }\n"
                                          "        ],\n"
                                          "        \"name\": \"getContractBalance\",\n"
                                          "        \"outputs\": [\n"
                                          "            {\n"
                                          "                \"internalType\": \"uint256\",\n"
                                          "                \"name\": \"\",\n"
                                          "                \"type\": \"uint256\"\n"
                                          "            }\n"
                                          "        ],\n"
                                          "        \"stateMutability\": \"view\",\n"
                                          "        \"type\": \"function\"\n"
                                          "    }");
  }

  namespace NativeWrapper {
    json withdraw = json::parse("    {\n"
                                "        \"inputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"uint256\",\n"
                                "                \"name\": \"value\",\n"
                                "                \"type\": \"uint256\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"name\": \"withdraw\",\n"
                                "        \"outputs\": [],\n"
                                "        \"stateMutability\": \"payable\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json deposit = json::parse("    {\n"
                               "        \"inputs\": [],\n"
                               "        \"name\": \"deposit\",\n"
                               "        \"outputs\": [],\n"
                               "        \"stateMutability\": \"payable\",\n"
                               "        \"type\": \"function\"\n"
                               "    }");
  }

  namespace ContractManager {
    json createNewERC20Contract = json::parse("{\n"
                                              "        \"inputs\": [\n"
                                              "            {\n"
                                              "                \"internalType\": \"string\",\n"
                                              "                \"name\": \"erc20name\",\n"
                                              "                \"type\": \"string\"\n"
                                              "            },\n"
                                              "            {\n"
                                              "                \"internalType\": \"string\",\n"
                                              "                \"name\": \"erc20symbol\",\n"
                                              "                \"type\": \"string\"\n"
                                              "            },\n"
                                              "            {\n"
                                              "                \"internalType\": \"uint8\",\n"
                                              "                \"name\": \"erc20decimals\",\n"
                                              "                \"type\": \"uint8\"\n"
                                              "            },\n"
                                              "            {\n"
                                              "                \"internalType\": \"uint256\",\n"
                                              "                \"name\": \"mintValue\",\n"
                                              "                \"type\": \"uint256\"\n"
                                              "            }\n"
                                              "        ],\n"
                                              "        \"name\": \"createNewERC20Contract\",\n"
                                              "        \"outputs\": [],\n"
                                              "        \"stateMutability\": \"nonpayable\",\n"
                                              "        \"type\": \"function\"\n"
                                              "    }");

    json createNewERC20WrapperContract = json::parse("    {\n"
                                                     "        \"inputs\": [],\n"
                                                     "        \"name\": \"createNewERC20WrapperContract\",\n"
                                                     "        \"outputs\": [],\n"
                                                     "        \"stateMutability\": \"nonpayable\",\n"
                                                     "        \"type\": \"function\"\n"
                                                     "    }");

    json createNewNativeWrapperContract = json::parse("{\n"
                                                      "        \"inputs\": [\n"
                                                      "            {\n"
                                                      "                \"internalType\": \"string\",\n"
                                                      "                \"name\": \"erc20_name\",\n"
                                                      "                \"type\": \"string\"\n"
                                                      "            },\n"
                                                      "            {\n"
                                                      "                \"internalType\": \"string\",\n"
                                                      "                \"name\": \"erc20_symbol\",\n"
                                                      "                \"type\": \"string\"\n"
                                                      "            },\n"
                                                      "            {\n"
                                                      "                \"internalType\": \"uint8\",\n"
                                                      "                \"name\": \"erc20_decimals\",\n"
                                                      "                \"type\": \"uint8\"\n"
                                                      "            }\n"
                                                      "        ],\n"
                                                      "        \"name\": \"createNewNativeWrapperContract\",\n"
                                                      "        \"outputs\": [],\n"
                                                      "        \"stateMutability\": \"nonpayable\",\n"
                                                      "        \"type\": \"function\"\n"
                                                      "    }");

    json createNewSimpleContract = json::parse("{\n"
                                               "  \"inputs\": [\n"
                                               "    {\n"
                                               "      \"internalType\": \"string\",\n"
                                               "      \"name\": \"name_\",\n"
                                               "      \"type\": \"string\"\n"
                                               "    },\n"
                                               "    {\n"
                                               "      \"internalType\": \"uint256\",\n"
                                               "      \"name\": \"number_\",\n"
                                               "      \"type\": \"uint256\"\n"
                                               "    },\n"
                                               "    {\n"
                                               "      \"components\": [\n"
                                               "        {\n"
                                               "          \"internalType\": \"string\",\n"
                                               "          \"type\": \"string\"\n"
                                               "        },\n"
                                               "        {\n"
                                               "          \"internalType\": \"uint256\",\n"
                                               "          \"type\": \"uint256\"\n"
                                               "        }\n"
                                               "      ],\n"
                                               "      \"name\": \"tuple_\",\n"
                                               "      \"type\": \"tuple\"\n"
                                               "    }\n"
                                               "  ],\n"
                                               "  \"name\": \"createNewSimpleContractContract\",\n"
                                               "  \"outputs\": [],\n"
                                               "  \"stateMutability\": \"nonpayable\",\n"
                                               "  \"type\": \"function\"\n"
                                               "}\n");

    json createNewDEXV2PairContract = json::parse("    {\n"
                                                  "        \"inputs\": [],\n"
                                                  "        \"name\": \"createNewDEXV2PairContract\",\n"
                                                  "        \"outputs\": [],\n"
                                                  "        \"stateMutability\": \"nonpayable\",\n"
                                                  "        \"type\": \"function\"\n"
                                                  "    }");

    json createNewDEXV2FactoryContract = json::parse("    {\n"
                                                     "        \"inputs\": [\n"
                                                     "            {\n"
                                                     "                \"internalType\": \"address\",\n"
                                                     "                \"name\": \"_feeToSetter\",\n"
                                                     "                \"type\": \"address\"\n"
                                                     "            }\n"
                                                     "        ],\n"
                                                     "        \"name\": \"createNewDEXV2FactoryContract\",\n"
                                                     "        \"outputs\": [],\n"
                                                     "        \"stateMutability\": \"nonpayable\",\n"
                                                     "        \"type\": \"function\"\n"
                                                     "    }");

    json createNewDEXV2Router02Contract = json::parse("    {\n"
                                                      "        \"inputs\": [\n"
                                                      "            {\n"
                                                      "                \"internalType\": \"address\",\n"
                                                      "                \"name\": \"factory\",\n"
                                                      "                \"type\": \"address\"\n"
                                                      "            },\n"
                                                      "            {\n"
                                                      "                \"internalType\": \"address\",\n"
                                                      "                \"name\": \"wrappedNative\",\n"
                                                      "                \"type\": \"address\"\n"
                                                      "            }\n"
                                                      "        ],\n"
                                                      "        \"name\": \"createNewDEXV2Router02Contract\",\n"
                                                      "        \"outputs\": [],\n"
                                                      "        \"stateMutability\": \"nonpayable\",\n"
                                                      "        \"type\": \"function\"\n"
                                                      "    }");

    json createNewERC721Contract = json::parse("{\n"
                                               "        \"inputs\": [\n"
                                               "            {\n"
                                               "                \"internalType\": \"string\",\n"
                                               "                \"name\": \"erc721name\",\n"
                                               "                \"type\": \"string\"\n"
                                               "            },\n"
                                               "            {\n"
                                               "                \"internalType\": \"string\",\n"
                                               "                \"name\": \"erc721symbol\",\n"
                                               "                \"type\": \"string\"\n"
                                               "            }\n"
                                               "        ],\n"
                                               "        \"name\": \"createNewERC721Contract\",\n"
                                               "        \"outputs\": [],\n"
                                               "        \"stateMutability\": \"nonpayable\",\n"
                                               "        \"type\": \"function\"\n"
                                               "    }");

    json createNewThrowTestAContract = json::parse("    {\n"
                                                   "        \"inputs\": [],\n"
                                                   "        \"name\": \"createNewThrowTestAContract\",\n"
                                                   "        \"outputs\": [],\n"
                                                   "        \"stateMutability\": \"nonpayable\",\n"
                                                   "        \"type\": \"function\"\n"
                                                   "    }");

    json createNewThrowTestBContract = json::parse("    {\n"
                                                   "        \"inputs\": [],\n"
                                                   "        \"name\": \"createNewThrowTestBContract\",\n"
                                                   "        \"outputs\": [],\n"
                                                   "        \"stateMutability\": \"nonpayable\",\n"
                                                   "        \"type\": \"function\"\n"
                                                   "    }");

    json createNewThrowTestCContract = json::parse("    {\n"
                                                   "        \"inputs\": [],\n"
                                                   "        \"name\": \"createNewThrowTestCContract\",\n"
                                                   "        \"outputs\": [],\n"
                                                   "        \"stateMutability\": \"nonpayable\",\n"
                                                   "        \"type\": \"function\"\n"
                                                   "    }");

    json getDeployedContracts = json::parse("    {\n"
                                            "        \"inputs\": [],\n"
                                            "        \"name\": \"getDeployedContracts\",\n"
                                            "        \"outputs\": [\n"
                                            "            {\n"
                                            "                \"internalType\": \"string[]\",\n"
                                            "                \"name\": \"\",\n"
                                            "                \"type\": \"string[]\"\n"
                                            "            },\n"
                                            "            {\n"
                                            "                \"internalType\": \"address[]\",\n"
                                            "                \"name\": \"\",\n"
                                            "                \"type\": \"address[]\"\n"
                                            "            }\n"
                                            "        ],\n"
                                            "        \"stateMutability\": \"view\",\n"
                                            "        \"type\": \"function\"\n"
                                            "    }");
  }

  namespace SimpleContract {
    json getNamesAndNumbersInArrayOfArrays = json::parse("  {\n"
                                                        "    \"inputs\": [\n"
                                                        "      {\n"
                                                        "        \"internalType\": \"uint256\",\n"
                                                        "        \"name\": \"i\",\n"
                                                        "        \"type\": \"uint256\"\n"
                                                        "      }\n"
                                                        "    ],\n"
                                                        "    \"name\": \"getNamesAndNumbersInArrayOfArrays\",\n"
                                                        "    \"outputs\": [\n"
                                                        "      {\n"
                                                        "        \"components\": [\n"
                                                        "          {\n"
                                                        "            \"internalType\": \"string\",\n"
                                                        "            \"type\": \"string\"\n"
                                                        "          },\n"
                                                        "          {\n"
                                                        "            \"internalType\": \"uint256\",\n"
                                                        "            \"type\": \"uint256\"\n"
                                                        "          }\n"
                                                        "        ],\n"
                                                        "        \"type\": \"tuple[][]\"\n"
                                                        "      }\n"
                                                        "    ],\n"
                                                        "    \"stateMutability\": \"view\",\n"
                                                        "    \"type\": \"function\"\n"
                                                        "  }");

    json getNamesAndNumbersInTuple = json::parse("    {\n"
                                                "        \"inputs\": [\n"
                                                "            {\n"
                                                "                \"internalType\": \"uint256\",\n"
                                                "                \"name\": \"i\",\n"
                                                "                \"type\": \"uint256\"\n"
                                                "            }\n"
                                                "        ],\n"
                                                "        \"name\": \"getNamesAndNumbersInTuple\",\n"
                                                "        \"outputs\": [\n"
                                                "            {\n"
                                                "                \"components\": [\n"
                                                "                    {\n"
                                                "                        \"internalType\": \"string\",\n"
                                                "                        \"type\": \"string\"\n"
                                                "                    },\n"
                                                "                    {\n"
                                                "                        \"internalType\": \"uint256\",\n"
                                                "                        \"type\": \"uint256\"\n"
                                                "                    }\n"
                                                "                ],\n"
                                                "                \"type\": \"tuple[]\"\n"
                                                "            }\n"
                                                "        ],\n"
                                                "        \"stateMutability\": \"view\",\n"
                                                "        \"type\": \"function\"\n"
                                                "    }");

    json getNameAndNumber = json::parse("    {\n"
                                       "        \"inputs\": [],\n"
                                       "        \"name\": \"getNameAndNumber\",\n"
                                       "        \"outputs\": [\n"
                                       "            {\n"
                                       "                \"components\": [\n"
                                       "                    {\n"
                                       "                        \"internalType\": \"string\",\n"
                                       "                        \"type\": \"string\"\n"
                                       "                    },\n"
                                       "                    {\n"
                                       "                        \"internalType\": \"uint256\",\n"
                                       "                        \"type\": \"uint256\"\n"
                                       "                    }\n"
                                       "                ],\n"
                                       "                \"type\": \"tuple\"\n"
                                       "            }\n"
                                       "        ],\n"
                                       "        \"stateMutability\": \"view\",\n"
                                       "        \"type\": \"function\"\n"
                                       "    }");

    json getNumbers = json::parse("    {\n"
                                 "        \"inputs\": [\n"
                                 "            {\n"
                                 "                \"internalType\": \"uint256\",\n"
                                 "                \"name\": \"i\",\n"
                                 "                \"type\": \"uint256\"\n"
                                 "            }\n"
                                 "        ],\n"
                                 "        \"name\": \"getNumbers\",\n"
                                 "        \"outputs\": [\n"
                                 "            {\n"
                                 "                \"internalType\": \"uint256[]\",\n"
                                 "                \"name\": \"\",\n"
                                 "                \"type\": \"uint256[]\"\n"
                                 "            }\n"
                                 "        ],\n"
                                 "        \"stateMutability\": \"view\",\n"
                                 "        \"type\": \"function\"\n"
                                 "    }");

    json getNumber = json::parse("    {\n"
                                "        \"inputs\": [],\n"
                                "        \"name\": \"getNumber\",\n"
                                "        \"outputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"uint256\",\n"
                                "                \"name\": \"\",\n"
                                "                \"type\": \"uint256\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"stateMutability\": \"view\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json getName = json::parse("    {\n"
                               "        \"inputs\": [],\n"
                               "        \"name\": \"getName\",\n"
                               "        \"outputs\": [\n"
                               "            {\n"
                               "                \"internalType\": \"string\",\n"
                               "                \"name\": \"\",\n"
                               "                \"type\": \"string\"\n"
                               "            }\n"
                               "        ],\n"
                               "        \"stateMutability\": \"view\",\n"
                               "        \"type\": \"function\"\n"
                               "    }");

    json getTuple = json::parse("{\n"
                                "  \"inputs\": [],\n"
                                "  \"name\": \"getTuple\",\n"
                                "  \"outputs\": [\n"
                                "    {\n"
                                "      \"components\": [\n"
                                "        {\n"
                                "          \"internalType\": \"string\",\n"
                                "          \"type\": \"string\"\n"
                                "        },\n"
                                "        {\n"
                                "          \"internalType\": \"uint256\",\n"
                                "          \"type\": \"uint256\"\n"
                                "        }\n"
                                "      ],\n"
                                "      \"type\": \"tuple\"\n"
                                "    }\n"
                                "  ],\n"
                                "  \"stateMutability\": \"view\",\n"
                                "  \"type\": \"function\"\n"
                                "}\n");

    json setNamesAndNumbersInArrayOfArrays = json::parse("  {\n"
                                                        "    \"inputs\": [\n"
                                                        "      {\n"
                                                        "        \"components\": [\n"
                                                        "          {\n"
                                                        "            \"internalType\": \"string\",\n"
                                                        "            \"type\": \"string\"\n"
                                                        "          },\n"
                                                        "          {\n"
                                                        "            \"internalType\": \"uint256\",\n"
                                                        "            \"type\": \"uint256\"\n"
                                                        "          }\n"
                                                        "        ],\n"
                                                        "        \"name\": \"argNameAndNumber\",\n"
                                                        "        \"type\": \"tuple[][]\"\n"
                                                        "      }\n"
                                                        "    ],\n"
                                                        "    \"name\": \"setNamesAndNumbersInArrayOfArrays\",\n"
                                                        "    \"outputs\": [],\n"
                                                        "    \"stateMutability\": \"nonpayable\",\n"
                                                        "    \"type\": \"function\"\n"
                                                        "  }");

    json setNamesAndNumbersInTuple = json::parse("    {\n"
                                                "        \"inputs\": [\n"
                                                "            {\n"
                                                "                \"components\": [\n"
                                                "                    {\n"
                                                "                        \"internalType\": \"string\",\n"
                                                "                        \"type\": \"string\"\n"
                                                "                    },\n"
                                                "                    {\n"
                                                "                        \"internalType\": \"uint256\",\n"
                                                "                        \"type\": \"uint256\"\n"
                                                "                    }\n"
                                                "                ],\n"
                                                "                \"name\": \"argNameAndNumber\",\n"
                                                "                \"type\": \"tuple[]\"\n"
                                                "            }\n"
                                                "        ],\n"
                                                "        \"name\": \"setNamesAndNumbersInTuple\",\n"
                                                "        \"outputs\": [],\n"
                                                "        \"stateMutability\": \"nonpayable\",\n"
                                                "        \"type\": \"function\"\n"
                                                "    }");

    json getNames = json::parse("    {\n"
                                "        \"inputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"uint256\",\n"
                                "                \"name\": \"i\",\n"
                                "                \"type\": \"uint256\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"name\": \"getNames\",\n"
                                "        \"outputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"string[]\",\n"
                                "                \"name\": \"\",\n"
                                "                \"type\": \"string[]\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"stateMutability\": \"view\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json setNumbers = json::parse("    {\n"
                                 "        \"inputs\": [\n"
                                 "            {\n"
                                 "                \"internalType\": \"uint256[]\",\n"
                                 "                \"name\": \"argNumber\",\n"
                                 "                \"type\": \"uint256[]\"\n"
                                 "            }\n"
                                 "        ],\n"
                                 "        \"name\": \"setNumbers\",\n"
                                 "        \"outputs\": [],\n"
                                 "        \"stateMutability\": \"nonpayable\",\n"
                                 "        \"type\": \"function\"\n"
                                 "    }");

    json setNumber = json::parse("    {\n"
                                "        \"inputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"uint256\",\n"
                                "                \"name\": \"argNumber\",\n"
                                "                \"type\": \"uint256\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"name\": \"setNumber\",\n"
                                "        \"outputs\": [],\n"
                                "        \"stateMutability\": \"nonpayable\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json setNamesAndNumbers = json::parse("    {\n"
                                         "        \"inputs\": [\n"
                                         "            {\n"
                                         "                \"internalType\": \"string[]\",\n"
                                         "                \"name\": \"argName\",\n"
                                         "                \"type\": \"string[]\"\n"
                                         "            },\n"
                                         "            {\n"
                                         "                \"internalType\": \"uint256[]\",\n"
                                         "                \"name\": \"argNumber\",\n"
                                         "                \"type\": \"uint256[]\"\n"
                                         "            }\n"
                                         "        ],\n"
                                         "        \"name\": \"setNamesAndNumbers\",\n"
                                         "        \"outputs\": [],\n"
                                         "        \"stateMutability\": \"nonpayable\",\n"
                                         "        \"type\": \"function\"\n"
                                         "    }");

    json setNames = json::parse("    {\n"
                                "        \"inputs\": [\n"
                                "            {\n"
                                "                \"internalType\": \"string[]\",\n"
                                "                \"name\": \"argName\",\n"
                                "                \"type\": \"string[]\"\n"
                                "            }\n"
                                "        ],\n"
                                "        \"name\": \"setNames\",\n"
                                "        \"outputs\": [],\n"
                                "        \"stateMutability\": \"nonpayable\",\n"
                                "        \"type\": \"function\"\n"
                                "    }");

    json getNamesAndNumbers = json::parse("{\n"
                                         "        \"inputs\": [\n"
                                         "            {\n"
                                         "                \"internalType\": \"uint256\",\n"
                                         "                \"name\": \"i\",\n"
                                         "                \"type\": \"uint256\"\n"
                                         "            }\n"
                                         "        ],\n"
                                         "        \"name\": \"getNamesAndNumbers\",\n"
                                         "        \"outputs\": [\n"
                                         "            {\n"
                                         "                \"components\": [\n"
                                         "                    {\n"
                                         "                        \"internalType\": \"string[]\",\n"
                                         "                        \"type\": \"string[]\"\n"
                                         "                    },\n"
                                         "                    {\n"
                                         "                        \"internalType\": \"uint256[]\",\n"
                                         "                        \"type\": \"uint256[]\"\n"
                                         "                    }\n"
                                         "                ],\n"
                                         "                \"type\": \"tuple\"\n"
                                         "            }\n"
                                         "        ],\n"
                                         "        \"stateMutability\": \"view\",\n"
                                         "        \"type\": \"function\"\n"
                                         "    }");

    json setName = json::parse("    {\n"
                               "        \"inputs\": [\n"
                               "            {\n"
                               "                \"internalType\": \"string\",\n"
                               "                \"name\": \"argName\",\n"
                               "                \"type\": \"string\"\n"
                               "            }\n"
                               "        ],\n"
                               "        \"name\": \"setName\",\n"
                               "        \"outputs\": [],\n"
                               "        \"stateMutability\": \"nonpayable\",\n"
                               "        \"type\": \"function\"\n"
                               "    }");

    json getNumberOverload = json::parse("{\n"
                                        "    \"inputs\": [\n"
                                        "      {\n"
                                        "        \"internalType\": \"uint256\",\n"
                                        "        \"name\": \"\",\n"
                                        "        \"type\": \"uint256\"\n"
                                        "      }\n"
                                        "    ],\n"
                                        "    \"name\": \"getNumber\",\n"
                                        "    \"outputs\": [\n"
                                        "      {\n"
                                        "        \"internalType\": \"uint256\",\n"
                                        "        \"name\": \"\",\n"
                                        "        \"type\": \"uint256\"\n"
                                        "      }\n"
                                        "    ],\n"
                                        "    \"stateMutability\": \"view\",\n"
                                        "    \"type\": \"function\"\n"
                                        "  }");

    json setTuple = json::parse("{\n"
                                "  \"inputs\": [\n"
                                "    {\n"
                                "      \"components\": [\n"
                                "        {\n"
                                "          \"internalType\": \"string\",\n"
                                "          \"type\": \"string\"\n"
                                "        },\n"
                                "        {\n"
                                "          \"internalType\": \"uint256\",\n"
                                "          \"type\": \"uint256\"\n"
                                "        }\n"
                                "      ],\n"
                                "      \"name\": \"argTupĺe\",\n"
                                "      \"type\": \"tuple\"\n"
                                "    }\n"
                                "  ],\n"
                                "  \"name\": \"setTuple\",\n"
                                "  \"outputs\": [],\n"
                                "  \"stateMutability\": \"nonpayable\",\n"
                                "  \"type\": \"function\"\n"
                                "}\n");

    json nameAndNumberTupleChanged = json::parse("{\n"
                                                "    \"anonymous\": false,\n"
                                                "    \"inputs\": [\n"
                                                "      {\n"
                                                "        \"components\": [\n"
                                                "          {\n"
                                                "            \"internalType\": \"string\",\n"
                                                "            \"type\": \"string\"\n"
                                                "          },\n"
                                                "          {\n"
                                                "            \"internalType\": \"uint256\",\n"
                                                "            \"type\": \"uint256\"\n"
                                                "          }\n"
                                                "        ],\n"
                                                "        \"indexed\": true,\n"
                                                "        \"name\": \"nameAndNumber\",\n"
                                                "        \"type\": \"tuple\"\n"
                                                "      }\n"
                                                "    ],\n"
                                                "    \"name\": \"nameAndNumberTupleChanged\",\n"
                                                "    \"type\": \"event\"\n"
                                                "  }");

    json nameAndNumberChanged = json::parse("{\n"
                                           "    \"anonymous\": false,\n"
                                           "    \"inputs\": [\n"
                                           "      {\n"
                                           "        \"indexed\": true,\n"
                                           "        \"internalType\": \"string\",\n"
                                           "        \"name\": \"name\",\n"
                                           "        \"type\": \"string\"\n"
                                           "      },\n"
                                           "      {\n"
                                           "        \"indexed\": true,\n"
                                           "        \"internalType\": \"uint256\",\n"
                                           "        \"name\": \"number\",\n"
                                           "        \"type\": \"uint256\"\n"
                                           "      }\n"
                                           "    ],\n"
                                           "    \"name\": \"nameAndNumberChanged\",\n"
                                           "    \"type\": \"event\"\n"
                                           "  }");

    json numberChanged = json::parse("{\n"
                                    "    \"anonymous\": false,\n"
                                    "    \"inputs\": [\n"
                                    "      {\n"
                                    "        \"indexed\": false,\n"
                                    "        \"internalType\": \"uint256\",\n"
                                    "        \"name\": \"number\",\n"
                                    "        \"type\": \"uint256\"\n"
                                    "      }\n"
                                    "    ],\n"
                                    "    \"name\": \"numberChanged\",\n"
                                    "    \"type\": \"event\"\n"
                                    "  }");

    json nameChanged = json::parse("{\n"
                                   "    \"anonymous\": false,\n"
                                   "    \"inputs\": [\n"
                                   "      {\n"
                                   "        \"indexed\": true,\n"
                                   "        \"internalType\": \"string\",\n"
                                   "        \"name\": \"name\",\n"
                                   "        \"type\": \"string\"\n"
                                   "      }\n"
                                   "    ],\n"
                                   "    \"name\": \"nameChanged\",\n"
                                   "    \"type\": \"event\"\n"
                                   "  }");

    json tupleChanged = json::parse("{\n"
                                    "  \"anonymous\": false,\n"
                                    "  \"inputs\": [\n"
                                    "    {\n"
                                    "      \"components\": [\n"
                                    "        {\n"
                                    "          \"internalType\": \"string\",\n"
                                    "          \"type\": \"string\"\n"
                                    "        },\n"
                                    "        {\n"
                                    "          \"internalType\": \"uint256\",\n"
                                    "          \"type\": \"uint256\"\n"
                                    "        }\n"
                                    "      ],\n"
                                    "      \"indexed\": true,\n"
                                    "      \"name\": \"tuple\",\n"
                                    "      \"type\": \"tuple\"\n"
                                    "    }\n"
                                    "  ],\n"
                                    "  \"name\": \"tupleChanged\",\n"
                                    "  \"type\": \"event\"\n"
                                    "}");
  }
}

