// Randomness has to be reimplemented as a brand-new protocol and "side-chain" to the transaction block chain
//  provided by CometBFT.
// The idea is that State::processBlock() will take a CometBFT block AND a block from this side-chain that is
//  built by running a P2P secure random generation protocol between the exact same validator set for that
//  transaction block chain block. This side-chain block has the secure random value and >=2/3+1 signatures from
//  the validator set at that transaction chain block height, and the secure random value is bound to the
//  transaction chain block that was proposed for that round (it is bound to the actual CometBFT block
//  proposal generated by Blockchain::buildBlockProposal / ABCI PrepareProposal, which all participants on
//  the random generator have to explicitly sign, and that signature goes into the side-chain block.)