include(CheckTypeSize)
check_type_size("int64_t" SIZEOF_INT64_T)
check_type_size("long long" SIZEOF_LONG_LONG)
check_type_size("long" SIZEOF_LONG)

if(SIZEOF_INT64_T EQUAL "8")
  set(INT64_T "int64_t")
elseif(SIZEOF_LONG EQUAL "8")
  set(INT64_T "long")
elseif(SIZEOF_LONG_LONG EQUAL "8")
  set(INT64_T "long long")
else()
  message(FATAL_ERROR "Can't find suitable int64_t")
endif()
message(STATUS "Found int64_t: ${INT64_T}")

check_type_size("char" SIZEOF_CHAR)
if(SIZEOF_CHAR EQUAL "1")
  set(CHAR "char")
else()
  message(FATAL_ERROR "Can't find suitable char")
endif()
message(STATUS "Found char: ${CHAR}")
