name: C++ Build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Change JSON file permissions
        run: chmod +r tests/*.json

      - name: Run docker container and execute commands
        run: |
          docker run -v $GITHUB_WORKSPACE:/work -w /work debian:bookworm /bin/bash -c "\
          apt-get update && \
          DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake tmux clang-tidy autoconf libtool pkg-config libabsl-dev libboost-all-dev libc-ares-dev libcrypto++-dev libgrpc-dev libgrpc++-dev librocksdb-dev libscrypt-dev libsnappy-dev libssl-dev zlib1g-dev openssl protobuf-compiler protobuf-compiler-grpc libprotobuf-dev git doxygen && \
          apt-get install -y ca-certificates && \
          cmake -S . -B build && \
          cmake --build build && \
          cd build && \
          ./orbitersdkd-tests -d yes ~[rdpos] ~[state] ~[p2p] && \
          cd .. && \
          mkdir docs && \
          doxygen Doxyfile"

      - name: Publish Documentation
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: docs
