name: C++ Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build environment
        uses: actions/setup-cxx@v1
        with:
          cxx-version: '20'

      - name: Build with make
        run: make
