name: C++ Build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build_test_and_analyse:
    runs-on: [self-hosted, linux, x64]
    env:
      # https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/
      # Directory where build-wrapper output will be placed
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
      SONAR_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      TARGET_DIR: "/home/actions/actions-runner/_work/bdk-cpp/bdk-cpp"
    steps:
      - name: Clone or pull
        shell: bash
        run: git -C ${{env.TARGET_DIR}} pull || git clone https://github.com/${{ github.repository }} ${{ env.TARGET_DIR}}
      - name: Fetch referencies
        run: git -C ${{env.TARGET_DIR}} fetch origin +refs/pull/*:refs/remotes/origin/pr/*
      - name: Checkout to referencie
        shell: bash
        run: |
             b=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 16)
             n=$(echo "${{ github.ref_name }}" | tr "/" " " | awk '{print $1}')
             t=$(echo "${{ github.ref_name }}" | tr "/" " " | awk '{print $2}')
             git -C ${{env.TARGET_DIR}} checkout -b "$b" "origin/pr/$n/$t"
      - name: Build the container
        run: ./scripts/auto.sh -s bdk build
      - name: Stop the container
        run: ./scripts/auto.sh -s bdk stop
      - name: Restart the container
        run: ./scripts/auto.sh -s bdk up
      - name: Clean previos build (if any)
        run: ./scripts/auto.sh -s bdk exec 'make -C /bdk-cpp/build clean' || true
      - name: Configure MOLD linker
        run: ./scripts/auto.sh -s bdk exec 'cmake -S /bdk-cpp -B /bdk-cpp/build
             -DSONARQUBE_ANALYSIS=ON -DDEBUG=OFF
             -DCMAKE_EXE_LINKER_FLAGS=\"-fuse-ld=mold\"
             -DCMAKE_SHARED_LINKER_FLAGS=\"-fuse-ld=mold\"'
      - name: Build with SonarQube BuildWrapper + CMake
        run: ./scripts/auto.sh -s bdk exec \
             'build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }}
              cmake --build /bdk-cpp/build/ --config Release -- -j $(nproc)'
      - name: Run Tests
        run: ./scripts/auto.sh -s bdk exec \
             '/bdk-cpp/build/src/bins/bdkd-tests/bdkd-tests -d yes'
      - name: Run SonarQube Scanner
        run: ./scripts/auto.sh -s bdk exec \
             'env SONAR_TOKEN=${{ env.SONAR_TOKEN }} sonar-scanner
             --define sonar.cfamily.build-wrapper-output=${{ env.BUILD_WRAPPER_OUT_DIR }}
             --define sonar.coverageReportPaths=coverage.xml'
      # - name: Build the project
      #   run: ./scripts/auto.sh -s bdk exec 'cmake --build /bdk-cpp/build'
      # documentation:
      # - name: Generate Doxygen Documentation
      #   run: ./scripts/auto.sh -s bdk exec 'doxygen /bdk-cpp/Doxyfile'
      # - name: Publish Documentation
      #   uses: actions/upload-artifact@v4
      #   with:
      #   name: Documentation
      #   path: docs
