name: C++ Build

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Install GCC 12.2.0
        run: |
          sudo apt-get install -y libmpc-dev
          wget https://ftp.gnu.org/gnu/gcc/gcc-12.2.0/gcc-12.2.0.tar.gz
          tar xf gcc-12.2.0.tar.gz
          cd gcc-12.2.0
          ./contrib/download_prerequisites
          ./configure -v --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --prefix=/usr/local/gcc-12.2.0 --enable-checking=release --enable-languages=c,c++,fortran --disable-multilib --program-suffix=-12.2.0
          make -j$(nproc)
          sudo make install-strip
          echo "/usr/local/gcc-12.2.0/bin" >> $GITHUB_PATH
          echo "/usr/local/gcc-12.2.0/lib64" >> $GITHUB_ENV
          cd ..
          rm -rf gcc-12.2.0.tar.gz gcc-12.2.0
      
      - name: Print gcc version
        run: gcc --version

      - name: Install project dependencies
        run: sudo apt install build-essential cmake tmux clang-tidy autoconf libtool pkg-config libabsl-dev libboost-all-dev libc-ares-dev libcrypto++-dev libgrpc-dev libgrpc++-dev librocksdb-dev libscrypt-dev libsnappy-dev libssl-dev zlib1g-dev openssl protobuf-compiler protobuf-compiler-grpc

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build with CMake
        run: cmake --build build

      - name: Run Catch2 Tests
        working-directory: build
        run: ./orbitersdkd-tests -d yes
        
      - name: Generate Doxygen Documentation
        run: |
          mkdir docs
          doxygen Doxyfile

      - name: Publish Documentation
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: docs
