name: C++ Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake
      
      - name: Print gcc version
        run: gcc --version

      - name: Install project dependencies
        run: sudo apt install build-essential cmake tmux clang-tidy autoconf libtool pkg-config libabsl-dev libboost-all-dev libc-ares-dev libcrypto++-dev libgrpc-dev libgrpc++-dev librocksdb-dev libscrypt-dev libsnappy-dev libssl-dev zlib1g-dev openssl protobuf-compiler protobuf-compiler-grpc

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build with CMake
        run: cmake --build build

      - name: Run Catch2 Tests
        working-directory: build
        run: ./orbitersdkd-tests -d yes
        
      - name: Generate Doxygen Documentation
        run: |
          mkdir docs
          doxygen Doxyfile

      - name: Publish Documentation
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: docs
